"""Add admin and activity tracking columns to User model

Revision ID: 1e8a898f9714
Revises: 99394fae46ce
Create Date: 2025-06-14 19:48:17.086774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8a898f9714'
down_revision = '99394fae46ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_online')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
