"""Make semester_id nullable in Grade model

Revision ID: 230ebc601185
Revises: d4332ff7b66d
Create Date: 2025-06-14 15:06:23.004502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230ebc601185'
down_revision = 'd4332ff7b66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('semester_start_date')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('semester_start_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
