"""Add first_login column to User

Revision ID: 39b4bc736cc8
Revises: 4132ac8e155d
Create Date: 2025-06-14 12:48:28.880591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b4bc736cc8'
down_revision = '4132ac8e155d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_login')

    # ### end Alembic commands ###
