"""Add semester column to Grade model

Revision ID: 4132ac8e155d
Revises: 42ba7e6641db
Create Date: 2025-06-14 12:26:07.531503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4132ac8e155d'
down_revision = '42ba7e6641db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
