"""Clean migration after revert

Revision ID: 42ba7e6641db
Revises: 
Create Date: 2025-06-14 00:50:29.037879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ba7e6641db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('gpa_scale', sa.VARCHAR(length=20), nullable=True),
    sa.Column('grade_format', sa.VARCHAR(length=20), nullable=True),
    sa.Column('a_plus', sa.FLOAT(), nullable=True),
    sa.Column('a', sa.FLOAT(), nullable=True),
    sa.Column('a_minus', sa.FLOAT(), nullable=True),
    sa.Column('b_plus', sa.FLOAT(), nullable=True),
    sa.Column('b', sa.FLOAT(), nullable=True),
    sa.Column('b_minus', sa.FLOAT(), nullable=True),
    sa.Column('c_plus', sa.FLOAT(), nullable=True),
    sa.Column('c', sa.FLOAT(), nullable=True),
    sa.Column('c_minus', sa.FLOAT(), nullable=True),
    sa.Column('d_plus', sa.FLOAT(), nullable=True),
    sa.Column('d', sa.FLOAT(), nullable=True),
    sa.Column('d_minus', sa.FLOAT(), nullable=True),
    sa.Column('f', sa.FLOAT(), nullable=True),
    sa.Column('weight_regular', sa.FLOAT(), nullable=True),
    sa.Column('weight_honors', sa.FLOAT(), nullable=True),
    sa.Column('weight_ap', sa.FLOAT(), nullable=True),
    sa.Column('weight_ib', sa.FLOAT(), nullable=True),
    sa.Column('weight_de', sa.FLOAT(), nullable=True),
    sa.Column('gpa_cap', sa.FLOAT(), nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address', name=op.f('uq_user_email_address')),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
