"""Add use_credit_hours to User model

Revision ID: 99394fae46ce
Revises: 230ebc601185
Create Date: 2025-06-14 16:59:31.219138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99394fae46ce'
down_revision = '230ebc601185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_hours', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_credit_hours', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('use_credit_hours')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('credit_hours')

    # ### end Alembic commands ###
