"""Add semester_start_date to Grade

Revision ID: 9c0ae8bdebfb
Revises: 39b4bc736cc8
Create Date: 2025-06-14 13:45:35.379589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0ae8bdebfb'
down_revision = '39b4bc736cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('semester_start_date')

    # ### end Alembic commands ###
